### PR TITLE
fix: fix regression with toggle selection in legends

### LINKED ISSUE #1080: TypeError: mark.isUnnested is not a function. (In 'mark.isUnnested(fields[0])', 'mark.isUnnested' is undefined)
In the Seattle weather example when clicking on the legend. This may have been introduced by #1065.

### PR DESCRIPTION
**Pull request by domoritz**
fixes #1080

### CODE REVIEW

**Review by jheer — APPROVED** [review]

**Comment by SuMayaBee** [comment]
Thanks @domoritz! Saw your note on my PR #1065, it's a good catch with the legend edge case! 🙌
