### ISSUE TITLE
TypeError: mark.isUnnested is not a function. (In 'mark.isUnnested(fields[0])', 'mark.isUnnested' is undefined)

### ISSUE THREAD

**Issue by domoritz** [uwdata/mosaic#1080]
In the Seattle weather example when clicking on the legend. This may have been introduced by #1065.
